### ISSUE TITLE
How to choose TPMI in PUSCH？

### ISSUE THREAD

**Issue by modestlyh** [NVlabs/neural_rx#2]
Is it determined by the number of layers and the number of UE antenna ports?
I hope you can give me some guidance.

**Comment by SebastianCa** [comment]
Hi @modestlyh,
the exact choice depends on your system configuration. Please see [Sionna API doc](https://nvlabs.github.io/sionna/api/nr.html#sionna.nr.PUSCHConfig.tpmi) and [5G NR PUSCH tutorial](https://nvlabs.github.io/sionna/examples/5G_NR_PUSCH.html#Configuring-Multiple-Layers) for further details.

**Comment by modestlyh** [comment]
@SebastianCa I think there should be a table about the number of layers and the number of antenna ports to determine the TPMI, for example in the tutorial num_antenna_ports = 4, num_layers = 2, so TPMI=7 is selected, if num_antenna _ports = 2, num_layers = 2, how should that be chosen or should I traverse the TPMI based on some metric and choose the best one?

**Comment by SebastianCa** [comment]
The specific choice of the TPMI depends on the system configuration and is assumed to be provided by higher layers. This functionality is beyond the scope of the PUSCHReceiver.

For further details, please refer to Table 6.3.1.5-1 through Table 6.3.1.5-7 in 3GPP 38.211.

**Comment by modestlyh** [comment]
@SebastianCa Can I ask you another question, I'm not sure I've got the formula right if I want to calculate the throughput：
Throughput = 100 frame/s * 20 num_slots/frame * 14 num_symbols/slot  *  8 num_bits/symbol * BLER ,and get BLER by sim_ber function

**Comment by SebastianCa** [comment]
In principle that sounds correct (assuming 14 OFDM symbols per slot and 256 QAM). Iit depends on your exact definition of the throughput: a) raw throughput of the decoder (inlc. all DMRS symbols and parity bits from the FEC) or b) information bit throughput which would be something like `num_slots/s * tb_size/slot` where `tb_size` defines the number of transport block payload bits.

**Comment by modestlyh** [comment]
@SebastianCa Thank you so much！
