### ISSUE TITLE
 Question about tb_crc_status in PUSCHReceiver

### ISSUE THREAD

**Issue by xiaobaijh** [NVlabs/neural_rx#3]
Hello,

I am currently using the Sionna library for simulating communication links and have encountered a question regarding the tb_crc_status returned by the sionna.nr.PUSCHReceiver.

While I noticed that PUSCHReceiver can return both b_hat and tb_crc_status, it seems that in the subsequent processes, such as sim_ber, the tb_crc_status is not utilized.

Could you please clarify how tb_crc_status is intended to be used? Specifically, can this value be implemented in the **HARQ** (Hybrid Automatic Repeat reQuest)  mechanism?

Thank you for your assistance!

**Comment by SebastianCa** [comment]
Hi @xiaobaijh,

that's correct, the `tb_crc_status` is not used for the `sim_ber` function. There are multiple reasons: a) the CRC can be false positive and may lead to inaccurate results (in particular in the very low error rate regime) b) the CRC only detects block errors but cannot provide the exact number of bit errors (which is also tracked in the `sim_ber` function) and c) as we typically know the ground truth bits, there is no need to rely on the CRC. Keep in mind that you could still write a custom evaluation function that uses the CRC and provide it to the `sim_ber`.

The `tb_crc_status` is particularly useful for scenarios where the payload is unknown, e.g., when working with real-world datasets. As suggested it could be also used to trigger HARQ, however, that's currently not implemented in Sionna.

**Comment by xiaobaijh** [comment]
Thank yo for your assistance!

Are there any plans to implement HARQ in Sionna in the future? If so, could you provide any details or timelines regarding this feature?

Thank you for your hard work on this project!

**Comment by SebastianCa** [comment]
Unfortunately, we cannot comment on release dates for new features. Hope for your understanding.
