### ISSUE TITLE
Why LMMSE channel estimation is unsatisfactory？

### ISSUE THREAD

**Issue by modestlyh** [NVlabs/neural_rx#4]
![2x4_umi_0 0-20 0dB](https://github.com/user-attachments/assets/2cd669e2-117b-4f74-9854-5a93709d7b5a)
As the SNR increases, the curves of the two methods of LMMSE and LSlin channel estimation do not go down, but converge to a certain value, which is a bit strange.
I've set the same random number seed and other configurations are almost the same, but I'm doing it at 256qam, is there a reasonable explanation for this phenomenon?

**Comment by modestlyh** [comment]
Also, it's so strange that at high signal-to-noise ratios, BLER increases slightly instead

**Comment by jhoydis** [comment]
Hi @modestlyh,

We would need to know more about your setup. Most likely, the pilot pattern is not dense enough so that you get residual channel estimation errors which do not disappear with increasing SNR.

**Comment by modestlyh** [comment]
@jhoydis Thanks for the tip, I've found the cause, it was some problem with my configuration
